### ISSUE TITLE
If Branch has name PDW1-22-Example, it cannot pass check when set by Jira.

### ISSUE THREAD

**Issue by frohrbaugh** [worksome/jira-branch-name-validator-action#10]
Hi Everyone,

I am using Jira to make branches and its default thing is PDW1-22-Example, however, when I use this check to validate that commits, branches, and PRs match. The Branches are always showing an error "Error: Separator after JIRA id is not `_`, found -."

I tried to fork and test this myself by adjusting lines; however, it continues to push that error. Is there any advice as to changing this to allow PDW1-22-Example, instead of PDW1-22_Example since that is my Jira default? 

Appreciate all the help, just really confused on this one.

**Comment by olivernybroe** [comment]
Hi, the reason why we added this was actually laziness as we had a naming scheme saying `JIRA-123_something`. 

However that is not a requirement anymore and should anyway be handled outside of the action. 

Changing this would definity be fine with us :) 

I think the reason why you might have still received this error in your branch might have been because you have forgotten to build it. (github action requires the build files in the repo...)

**Comment by olivernybroe** [comment]
@FRohrbaugh I have released a v2.0.0 which should fix this for you 👍

**Comment by frohrbaugh** [comment]
@olivernybroe Thank you, I actually learned a lot doing this and your explanation makes so much sense now after a long weekend of trial and error. Thank you olivernybro, it means so much. I will start using this official action instead of my Frankenstein version.
